CURRENT_VERSION = "1.6"
TOOL_NAME = "Jet Fuel Rocket"

-- delimeters
DELIM = {}
DELIM.VEC = ":"
DELIM.STRINGS = "~"
DELIM.ENUM_PAIR = "&"
DELIM.OPTION_SET = "|"
DELIM.OPTION = ";"

-- registry related delimeters and strings
REG = {}
REG.DELIM = "."
REG.TOOL_KEY = "jetfuelrocket"
REG.TOOL_NAME = "savegame.mod.tool." .. REG.TOOL_KEY .. ".quarkhopper"
REG.TOOL_OPTION = "option"
REG.PREFIX_TOOL_OPTIONS = REG.TOOL_NAME .. REG.DELIM .. REG.TOOL_OPTION
REG.TOOL_KEYBIND = "keybind"
REG.PREFIX_TOOL_KEYBIND = REG.TOOL_NAME .. REG.DELIM .. REG.TOOL_KEYBIND

-- Keybinds
function setup_keybind(name, reg, default_key)
    local keybind = {["name"] = name, ["reg"] = reg}
    keybind.key = GetString(REG.PREFIX_TOOL_KEYBIND..REG.DELIM..keybind.reg)
    if keybind.key == "" then 
        keybind.key = default_key
        SetString(REG.PREFIX_TOOL_KEYBIND..REG.DELIM..keybind.reg, keybind.key)
    end
    return keybind
end

KEY = {}
KEY.FIRE = setup_keybind("Fire rocket", "fire", "LMB")
KEY.ALT_FIRE = setup_keybind("Fire beam", "alt_fire", "RMB")
KEY.CYCLE_FUSE = setup_keybind("cycle fuse distance", "cycle_fuse", "V")
KEY.CYCLE_EXPLOSION = setup_keybind("cycle simulation (explosion) size", "cycle_sim", "B")

keybind_options = {KEY.FIRE, KEY.ALT_FIRE, KEY.CYCLE_FUSE, KEY.CYCLE_EXPLOSION }

-- set on init
SIMULATION = {}

SIMULATION = {}
SIMULATION.SPARK_COLOR = Vec(7.7, 0.99, 0.65)
SIMULATION.SMOKE_COLOR = Vec(0, 0, 0.1)
SIMULATION.EXPLOSION_POWER = 2
SIMULATION.BLAST_SPEED = 1
SIMULATION.SPARK_HURT = 0.01
SIMULATION.HOLE_VOXEL_SOFT = 4
SIMULATION.HOLE_VOXEL_MEDIUM = 3
SIMULATION.HOLE_VOXEL_HARD = 2
SIMULATION.IGNITION_RADIUS = 5
SIMULATION.IGNITION_FREQ = 10
SIMULATION.IMPULSE_RADIUS = 6
SIMULATION.IMPULSE_TRIALS = 100
SIMULATION.SPARK_SPAWNS_UPPER = 14
SIMULATION.SPARK_SPAWNS_LOWER = 3
SIMULATION.SPLIT_FREQ_END = 100
SIMULATION.SPLIT_FREQ_INCREMENT = 1
SIMULATION.SPLIT_DIR_VARIATION = 0.8
SIMULATION.HIT_FOLLOW_MAX_SPEED = 2
SIMULATION.SPARK_DEATH_SPEED = 0.02
SIMULATION.SPLIT_SPEED_VARIATION = 0.1
SIMULATION.SPARK_SPEED_REDUCTION = 0.5
SIMULATION.PUFF_LIFE = 1.5
SIMULATION.SMOKE_LIFE = 1.5
SIMULATION.SPARK_TILE_RAD_MAX = 3
SIMULATION.SPARK_TILE_RAD_MIN = 2
SIMULATION.SMOKE_TILE_SIZE = 0.45
SIMULATION.SPARK_LIGHT_INTENSITY = 3
SIMULATION.SPARK_HURT_SCALE = 0.005
SIMULATION.IMPULSE_SCALE = 0.005
SIMULATION.PRESSURE_EFFECT_SCALE = 10^-3
SIMULATION.PUFF_CONTRAST = 0.65

ROCKET = {}
ROCKET.FIREBALL_DIR = Vec(0, 1, 0)
ROCKET.FIRE_DELAY = 0.5
ROCKET.ROCKET_SPEED = 1.5
ROCKET.ROCKET_MAX_DIST = 200
ROCKET.ROCKET_SAFE_DIST = 10.1
ROCKET.BOMB_ENERGY = 1000
ROCKET.BOMB_SPARKS = 100
ROCKET.SPLIT_SPEED = 0.5
ROCKET.SPLIT_FREQ_START = 10
ROCKET.FIZZLE_FREQ = 8
ROCKET.FIREBALL_RADIUS = 3
ROCKET.FIREBALL_SPARKS_MAX = 200
ROCKET.TORUS_PRESSURE = 1.3
ROCKET.VACUUM_PRESSURE = 0.02
ROCKET.INFLATION_PRESSURE = 0.6
ROCKET.IMPULSE_POWER = -5


JET = {}
JET.FIREBALL_DIR = Vec(0, 0, 0)
JET.SIM_SIZE = 300
JET.FIRE_DELAY = 0.001
JET.JET_MAX_DIST = 100
JET.SPLIT_FREQ_START = 10
JET.SPLIT_SPEED = 0.5
JET.TORUS_PRESSURE = 5.5
JET.VACUUM_PRESSURE = 0.02
JET.INFLATION_PRESSURE = 0.5
JET.FIREBALL_SPARKS_MAX = 200
JET.FIREBALL_RADIUS = 1.5
JET.BLAST_SPEED = 0.3
JET.FIZZLE_FREQ = 5
JET.IMPULSE_POWER = -5

-- UI 
UI = {}
UI.LEGEND_TEXT_SIZE = 20
UI.OPTION_TEXT_SIZE = 14
UI.OPTION_CONTROL_WIDTH = 300
