CURRENT_VERSION = "1.0"
TOOL_NAME = "Jet Fuel Rocket"

-- delimeters
DELIM = {}
DELIM.VEC = ":"
DELIM.STRINGS = "~"
DELIM.ENUM_PAIR = "&"
DELIM.OPTION_SET = "|"
DELIM.OPTION = ";"

-- registry related delimeters and strings
REG = {}
REG.DELIM = "."
REG.TOOL_KEY = "jetfuelrocket"
REG.TOOL_NAME = "savegame.mod.tool." .. REG.TOOL_KEY .. ".quarkhopper"
REG.TOOL_OPTION = "option"
REG.PREFIX_TOOL_OPTIONS = REG.TOOL_NAME .. REG.DELIM .. REG.TOOL_OPTION
REG.TOOL_KEYBIND = "keybind"
REG.PREFIX_TOOL_KEYBIND = REG.TOOL_NAME .. REG.DELIM .. REG.TOOL_KEYBIND

-- Keybinds
function setup_keybind(name, reg, default_key)
    local keybind = {["name"] = name, ["reg"] = reg}
    keybind.key = GetString(REG.PREFIX_TOOL_KEYBIND..REG.DELIM..keybind.reg)
    if keybind.key == "" then 
        keybind.key = default_key
        SetString(REG.PREFIX_TOOL_KEYBIND..REG.DELIM..keybind.reg, keybind.key)
    end
    return keybind
end

KEY = {}
KEY.FIRE = setup_keybind("Fire rocket", "fire", "LMB")
KEY.CYCLE_FUSE = setup_keybind("cycle fuse distance", "cycle_fuse", "V")

keybind_options = {KEY.FIRE, KEY.CYCLE_FUSE }

-- set on init
TOOL = {}
VALUES = {}

VALUES.SPARK_HURT_SCALE = 0.005
VALUES.IMPULSE_SCALE = 0.005
VALUES.PRESSURE_EFFECT_SCALE = 10^-3
VALUES.PUFF_CONTRAST = 0.65

JETFUEL.ROCKET_SPEED = 1
JETFUEL.ROCKET_MAX_DIST = 200
JETFUEL.SPARK_COLOR = Vec(7.7, 0.99, 0.65)
JETFUEL.SMOKE_COLOR = Vec(0, 0, 0.1)
JETFUEL.FIREBALL_DIR = Vec(0, 1, 0)
JETFUEL.SPARKS_SIMULATION = 1000
JETFUEL.BOMB_ENERGY = 1000
JETFUEL.BOMB_SPARKS = 100
JETFUEL.FIREBALL_SPARKS_MAX = 400
JETFUEL.FIREBALL_RADIUS = 3
JETFUEL.EXPLOSION_POWER = 2
JETFUEL.BLAST_SPEED = 1
JETFUEL.SPARK_HURT = 0.01
JETFUEL.HOLE_VOXEL_SOFT = 4
JETFUEL.HOLE_VOXEL_MEDIUM = 3
JETFUEL.HOLE_VOXEL_HARD = 2
JETFUEL.IGNITION_RADIUS = 5
JETFUEL.IGNITION_FREQ = 10
JETFUEL.IMPULSE_POWER = -5
JETFUEL.IMPULSE_RADIUS = 6
JETFUEL.IMPULSE_TRIALS = 100
JETFUEL.TORUS_PRESSURE = 1
JETFUEL.VACUUM_PRESSURE = 0.03
JETFUEL.INFLATION_PRESSURE = 0.5
JETFUEL.FIZZLE_FREQ = 8
JETFUEL.SPARK_SPAWNS_UPPER = 14
JETFUEL.SPARK_SPAWNS_LOWER = 3
JETFUEL.SPLIT_FREQ_START = 10
JETFUEL.SPLIT_FREQ_END = 100
JETFUEL.SPLIT_FREQ_INCREMENT = 1
JETFUEL.SPLIT_DIR_VARIATION = 0.8
JETFUEL.HIT_FOLLOW_MAX_SPEED = 2
JETFUEL.SPARK_DEATH_SPEED = 0.02
JETFUEL.SPLIT_SPEED = 0.5
JETFUEL.SPLIT_SPEED_VARIATION = 0.1
JETFUEL.SPARK_SPEED_REDUCTION = 0.5
JETFUEL.PUFF_LIFE = 1.5
JETFUEL.SMOKE_LIFE = 1.5
JETFUEL.SPARK_TILE_RAD_MAX = 3
JETFUEL.SPARK_TILE_RAD_MIN = 2
JETFUEL.SMOKE_TILE_SIZE = 0.45
JETFUEL.SPARK_LIGHT_INTENSITY = 3

-- UI 
UI = {}
UI.LEGEND_TEXT_SIZE = 20
UI.OPTION_TEXT_SIZE = 14
UI.OPTION_CONTROL_WIDTH = 300
